# Generated by Django 5.0.6 on 2024-06-12 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("result", "0002_alter_work_client_request_alter_work_documents_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "work",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="result.work",
                    ),
                ),
            ],
        ),
    ]
